import 'dart:math';

/// A single line of lyrics with timing and word-level span information.
class LyricLine {
  /// Line start time (relative to song).
  final Duration startTime;

  /// Line end time.
  final Duration endTime;

  /// Full text of this line.
  final String text;

  /// Optional translation (from KRC lyrics).
  final String? translatedText;

  /// Word/character-level timing spans.
  ///
  /// Even when the source format (plain LRC) has no per-word timing, spans
  /// are artificially generated by [tokenizeAndDistribute] so every line
  /// gets a smooth karaoke fill effect.
  final List<LyricSpan> spans;

  const LyricLine({
    required this.startTime,
    required this.endTime,
    required this.text,
    this.translatedText,
    required this.spans,
  });

  /// Returns the span that is active at [position], or null if none.
  LyricSpan? getSpanAt(Duration position) {
    if (spans.isEmpty) return null;
    try {
      return spans.firstWhere(
        (span) => position >= span.start && position <= span.end,
      );
    } catch (_) {
      return null;
    }
  }

  /// Returns intra-line fill progress (0.0 – 1.0) based on [position].
  double getLineProgress(Duration position) {
    final total = endTime.inMilliseconds - startTime.inMilliseconds;
    if (total <= 0) return 0.0;
    final current = position.inMilliseconds - startTime.inMilliseconds;
    return (current / total).clamp(0.0, 1.0);
  }

  /// Returns the full text with automatic spacing between CJK and Latin.
  String get lineText {
    if (spans.isEmpty) return '';
    final fullText = spans.map((s) => s.text).join().replaceAll(RegExp(r'\s+'), ' ');

    final buffer = StringBuffer();
    int lastType = 0;
    int getCharType(int code) {
      if (code == 32) return 0;
      if ((code >= 48 && code <= 57) ||
          (code >= 65 && code <= 90) ||
          (code >= 97 && code <= 122)) return 1;
      if (code <= 127) return 0;
      return 2;
    }

    for (final char in fullText.runes) {
      final currentType = getCharType(char);
      if (lastType != 0 && currentType != 0) {
        if ((lastType == 2 && currentType == 1) ||
            (lastType == 1 && currentType == 2)) {
          buffer.write(' ');
        }
      }
      buffer.write(String.fromCharCode(char));
      lastType = currentType;
    }

    return buffer.toString().trim();
  }
}

/// A single word/character with precise timing.
class LyricSpan {
  final String text;
  final Duration start;
  final Duration end;

  const LyricSpan({
    required this.text,
    required this.start,
    required this.end,
  });

  /// Fill progress for this single span (0.0 – 1.0).
  double getSpanProgress(Duration position) {
    final duration = end.inMilliseconds - start.inMilliseconds;
    if (duration <= 0) return position >= end ? 1.0 : 0.0;
    if (position < start) return 0.0;
    if (position > end) return 1.0;
    final current = position.inMilliseconds - start.inMilliseconds;
    return current / duration;
  }
}

// ---------------------------------------------------------------------------
//  LRC parser (adapted from Linx-Music)
// ---------------------------------------------------------------------------

/// Splits [text] into tokens and distributes [start]–[end] evenly across them.
///
/// For CJK text each character becomes its own span. For Latin text, words
/// split on spaces.  This gives every line a karaoke fill effect even when
/// the source LRC has no per-word timing.
List<LyricSpan> tokenizeAndDistribute(
    String text, Duration start, Duration end) {
  final spans = <LyricSpan>[];
  final totalMs = (end - start).inMilliseconds;

  if (totalMs <= 0 || text.isEmpty) {
    spans.add(LyricSpan(text: text, start: start, end: end));
    return spans;
  }

  final isEnglishLike = RegExp(r'[a-zA-Z]').hasMatch(text);
  List<String> tokens;

  if (isEnglishLike) {
    // 英文：按空格分词，保留空格到前一个单词
    final words = text.split(' ');
    tokens = [];
    for (int w = 0; w < words.length; w++) {
      tokens.add(words[w] + (w < words.length - 1 ? ' ' : ''));
    }
  } else {
    // 中文/日文：按单字分词
    tokens = text.split('');
  }

  tokens = tokens.where((t) => t.isNotEmpty).toList();
  if (tokens.isEmpty) return spans;

  final totalLen = tokens.fold(0, (sum, t) => sum + t.length);
  if (totalLen == 0) return spans;

  final msPerChar = totalMs.toDouble() / totalLen;
  Duration currentStart = start;

  for (final token in tokens) {
    final tokenMs = (msPerChar * token.length).round();
    final tokenDur = Duration(milliseconds: max(1, tokenMs));
    final tokenEnd = currentStart + tokenDur;
    spans.add(LyricSpan(text: token, start: currentStart, end: tokenEnd));
    currentStart = tokenEnd;
  }

  // 修正最后一个 span 的结束时间对齐行尾
  if (spans.isNotEmpty) {
    final last = spans.removeLast();
    spans.add(LyricSpan(text: last.text, start: last.start, end: end));
  }

  return spans;
}

/// Parses LRC-format lyrics into a sorted list of [LyricLine].
///
/// Handles metadata tags ([ti:], [ar:], [offset:], …), multiple timestamps
/// on the same line, and auto-generates per-word spans via
/// [tokenizeAndDistribute].
List<LyricLine> parseLyrics(String raw) {
  if (raw.trim().isEmpty) return [];

  final Map<int, List<String>> timeToTexts = {};
  final lines = raw.split(RegExp(r'\r\n|\r|\n'));

  int globalOffset = 0; // ms

  for (final line in lines) {
    final trimmed = line.trim();
    if (trimmed.isEmpty) continue;

    // 元数据标签 [key:value]
    final metaMatch =
        RegExp(r'^\[([a-zA-Z]+):(.*)\]$').firstMatch(trimmed);
    if (metaMatch != null) {
      final key = metaMatch.group(1)?.toLowerCase();
      final value = metaMatch.group(2)?.trim();
      if (key != null && value != null) {
        if (key == 'offset') {
          globalOffset = int.tryParse(value) ?? 0;
        }
      }
      continue;
    }

    // 时间戳 [mm:ss.xxx]
    final timeMatches =
        RegExp(r'\[(\d{2}):(\d{2})\.(\d{1,3})\]').allMatches(trimmed);
    if (timeMatches.isEmpty) continue;

    final text =
        trimmed.replaceAll(RegExp(r'\[\d{2}:\d{2}\.\d{1,3}\]'), '').trim();
    if (text.isEmpty) continue;

    for (final m in timeMatches) {
      final min = int.parse(m.group(1)!);
      final sec = int.parse(m.group(2)!);
      final msStr = m.group(3)!;
      final ms = int.parse(msStr.padRight(3, '0'));
      final timeMs = ((min * 60 + sec) * 1000 + ms) - globalOffset;

      timeToTexts.putIfAbsent(timeMs, () => []).add(text);
    }
  }

  final sortedTimes = timeToTexts.keys.toList()..sort();
  final lyricLines = <LyricLine>[];

  for (int i = 0; i < sortedTimes.length; i++) {
    final timeMs = sortedTimes[i];
    final texts = timeToTexts[timeMs]!;

    final mainText = texts.first;
    final Map<String, String> translations = {};
    if (texts.length > 1) {
      translations['zh'] = texts[1];
    }

    final nextTimeMs = (i + 1 < sortedTimes.length)
        ? sortedTimes[i + 1]
        : timeMs + 5000;

    final startTime = Duration(milliseconds: timeMs > 0 ? timeMs : 0);
    final endTime = Duration(milliseconds: nextTimeMs);

    lyricLines.add(LyricLine(
      startTime: startTime,
      endTime: endTime,
      text: mainText,
      translatedText: translations.isNotEmpty ? translations['zh'] : null,
      spans: tokenizeAndDistribute(mainText, startTime, endTime),
    ));
  }

  return lyricLines;
}

/// Helpers to find the current line / index from a sorted list.
int getLineIndexByProgress(List<LyricLine> lines, Duration position) {
  if (lines.isEmpty) return 0;
  final index = lines.lastIndexWhere((line) => position >= line.startTime);
  return index == -1 ? 0 : index;
}
